### ISSUE TITLE
Working with Partitions

### ISSUE THREAD

**Issue by arielmoraes** [glazkovalex/Rebus.Kafka#2]
How configure the Transport to work with Partitions? Are there any special configurations?

**Comment by glazkovalex** [comment]
> How configure the Transport to work with Partitions? Are there any special configurations?

Hello, @arielmoraes ! 
Thank you for your question. I don't quite understand your question, as transport is already working with Kafka's partitions. They are created automatically by the Kafka server, depending on the number of bus clients (customers). Specify please in what scenario, in what case of application of the Rebus bus you want to adjust partitions? 

If you want to increase the default number of log partitions wpar topic in order to create a worker queue, then this is done not in the bus transport, but on the Kafka server. By increasing the parameter "num.partitions" in the file: kafka/config/server.properties.

> The default number of log partitions per topic. More partitions allow greater parallelism for consumption, but this will also result in more files across the brokers.
> num.partitions=2

[Read more Kafka documentation.](https://kafka.apache.org/documentation/)

By setting the "num.partitions=2 " will allow you to see how the scaling of two workers ([Scaleout.Consumers](https://github.com/glazkovalex/Rebus.Kafka/tree/master/Examples/Scaleout.Consumers)) performing tasks created by one producer ([Scaleout.Producer](https://github.com/glazkovalex/Rebus.Kafka/tree/master/Examples/Scaleout.Producer)).

**Comment by glazkovalex** [comment]
Apparently, the request is allowed.
